sidebar:
  title: "Vejle Idrætshøjskoles Sange"
  image: "//images.weserv.nl/?url=https://drive.google.com/uc?id=10k7zuB8CRXnnKxBye_kIzKdBnO5uKGwi&w=300&a=attention&t=square"
  image_alt: "Vejle Idrætshøjskoles Sange"
  text: "De officielle sange er indspillet 2018 af Mille Sigsgaard Christensen, Charlotte Støjberg og Kristian Enevoldsen. **Køb den eller stream den fra din foretrukne musiktjeneste.**, fx [Google Play](https://play.google.com/music/listen#/album/Birdaib4zktzgwthhtd4uxlafta), [Itunes](https://itunes.apple.com/album/-/id1444457441), [Deezer](https://www.deezer.com/da/album/79792202), [Tidal](https://listen.tidal.com/album/99556066), [Spotify](https://play.spotify.com/album/6vpvN8PtyRg7wYLUqIdlbI), [YouSee](https://musik.yousee.dk/album/202470120/vejle-idraetshojskoles-sange)."
  nav: "songs"
